name: Docs

on:
  push:
    branches: [ "main" ]
    paths:
      - "README.md"

  pull_request:
    branches: [ "main" ]
    paths:
      - "README.md"

jobs:
  docs:
    runs-on: ubuntu-latest
    name: generate docs
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: panvimdoc
        uses: kdheepak/panvimdoc@v4.0.0
        with:
          vimdoc: triptych.nvim
          # Without the description panvimdoc will insert the nvim version and a date, which we don't want
          description: "Directory viewer inspired by Ranger"
          demojify: true
          version: "NVIM v0.9.0"
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "auto generate docs"
          branch: ${{ github.head_ref }}

